# Generated by Django 4.2.7 on 2023-11-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_rename_game_id_rating_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
