site_name: Technical Documentation
theme:
  name: readthedocs
nav:
  - Overview: index.md
  - Recommendation Algorithm: recommend.md
  - Database Models: models.md
  - API Endpoints: endpoints.md
  - RAWG Game API: rawg-api.md
